name: 单元测试

on:
  push:
    branches: [ main ]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: 检出
        uses: actions/checkout@v2

      - name: 部署环境
        run: docker-compose -f ".github/compose/docker-compose.yml" up -d

      - name: 安装 Golang
        uses: actions/setup-go@v2
        with:
          go-version: ~1.18

      - name: 启动测试
        run: go test -race -covermode atomic -coverprofile=covprofile ./...
        env:
          GO111MODULE: on
          HOSTS: nats://127.0.0.1:4222,nats://127.0.0.1:4223,nats://127.0.0.1:4224
          TOKEN: s3cr3t
          DATABASE: mongodb://super:123456@localhost:27017/admin

      - name: 推送覆盖率至 COVERALLS
        run: |
          go install github.com/mattn/goveralls@latest
          goveralls -coverprofile=covprofile -service=github
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}