name: Testing

on:
  push:
    branches: [ main ]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: docker-compose -f ".github/compose/docker-compose.yml" up -d
      - uses: actions/setup-go@v2
        with:
          go-version: ~1.21
      - run: go test -race -covermode atomic -coverprofile=covprofile ./...
        env:
          GO111MODULE: on
          HOSTS: nats://127.0.0.1:4222,nats://127.0.0.1:4223,nats://127.0.0.1:4224
          TOKEN: s3cr3t
      - run: |
          go install github.com/mattn/goveralls@latest
          goveralls -coverprofile=covprofile -service=github
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
